openapi: 3.0.3
info:
  version: 0.0.1
  title: VK
  description: |-
   System Design социальной сети для курса по System Design
servers:
  - url: https://vk.system.design.com/api/v1
paths:
  /friend:
    post:
      tags:
        - friend
      summary: Add new friend
      description: Add new friend or subscribing to updates of his events
      operationId: addFriend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
          application/xml:
            schema:
              $ref: '#/components/schemas/Friend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Friend'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/FriendResponse'
        '404':
          description: Friend not found
        '405':
          description: Add user not allowed
    get:
      tags:
        - friend
      summary: Get my friends
      description: Get my frineds and subscriptions
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFriendsResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/GetFriendsResponse'
        '405':
          description: Get friends not allowed
      
  /friend/{friendId}:
    delete:
      tags:
        - friend
      summary: Delete a user or unsubscribe from updates
      operationId: deleteFriend
      parameters:
        - name: friendId
          in: path
          description: ''
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteFriendResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/DeleteFriendResponse'
        '404':
          description: Friend not found
        '405':
          description: Add user not allowed
components:
  schemas:
    Friend:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 10
        frindId:
          type: integer
          format: int64
          example: 198772
      xml:
        name: friend
    FriendResponse:
      type: object
      properties:
        message:
          type: string
          example: "friend 198772 added successfully"
      xml:
        name: friendResponse
    DeleteFriendResponse:
      type: object
      properties:
        message:
          type: string
          example: "friend 10 deleted successfully"
      xml:
        name: DeleteFriendResponse
    Friends:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      xml:
        name: friends
    GetFriendsResponse:
      type: array
      xml:
        name: getFriendsResponse
        wrapped: true
      items:
        $ref: '#/components/schemas/Friends'
        